# -*- coding: utf-8 -*-
"""TourGuard AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjLoX5L-KbnCCpYgWKDtCGTKEXfq8kLJ
"""

!pip install ultralytics
!pip install gradio
!pip install twilio
!pip install opencv-python-headless

"""Load YOLO11n"""

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

"""Tour Registration"""

import gradio as gr

def upload_image(image):
    return image

demo = gr.Interface(
    fn=upload_image,
    inputs=gr.Image(type="numpy"),
    outputs=gr.Image()
)

demo.launch(share=True)

from ultralytics import YOLO
import gradio as gr

model = YOLO("yolo11n.pt")

def count_people(image):

    results = model(image)

    count = 0

    for box in results[0].boxes:

        cls = int(box.cls)

        if cls == 0:      # person
            count += 1

    return f"Tourists Detected: {count}"

demo = gr.Interface(
    fn=count_people,
    inputs=gr.Image(type="numpy"),
    outputs="text"
)

demo.launch(share=True)

# =====================================================
# INSTALL
# =====================================================
!pip install -q ultralytics gradio opencv-python-headless

# =====================================================
# IMPORTS
# =====================================================
import gradio as gr
import cv2
import numpy as np
from ultralytics import YOLO

# =====================================================
# LOAD MODEL
# =====================================================
# Better than yolo11n for crowd photos
model = YOLO("yolo11m.pt")

# =====================================================
# COUNT TOURISTS
# =====================================================
def count_tourists(image):

    image_bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

    results = model.predict(
        image_bgr,
        conf=0.15,
        imgsz=1280,
        verbose=False
    )

    result = results[0]

    person_count = 0

    for box in result.boxes:

        cls = int(box.cls[0])

        # COCO class 0 = person
        if cls == 0:
            person_count += 1

    annotated = result.plot()

    annotated = cv2.cvtColor(
        annotated,
        cv2.COLOR_BGR2RGB
    )

    return (
        annotated,
        f"Tourists Detected: {person_count}"
    )

# =====================================================
# GRADIO UI
# =====================================================
demo = gr.Interface(
    fn=count_tourists,
    inputs=gr.Image(type="numpy", label="Upload Group Photo"),
    outputs=[
        gr.Image(label="Detected Persons"),
        gr.Textbox(label="Result")
    ],
    title="TourGuard AI",
    description="AI Tourist Counting System"
)

demo.launch(share=True)

# =====================================================
# INSTALL
# =====================================================
!pip install -q ultralytics gradio opencv-python-headless

# =====================================================
# IMPORTS
# =====================================================
import cv2
import gradio as gr
from ultralytics import YOLO

# =====================================================
# LOAD MODEL
# =====================================================
model = YOLO("yolo11m.pt")

# =====================================================
# PERSON COUNT FUNCTION
# =====================================================
def count_people(image):

    results = model.predict(
        image,
        conf=0.15,
        imgsz=1280,
        verbose=False
    )

    count = 0

    for box in results[0].boxes:

        cls = int(box.cls[0])

        if cls == 0:      # person
            count += 1

    annotated = results[0].plot()

    annotated = cv2.cvtColor(
        annotated,
        cv2.COLOR_BGR2RGB
    )

    return count, annotated


# =====================================================
# COMPARE TOUR GROUPS
# =====================================================
def verify_group(start_image, current_image):

    expected_count, start_output = count_people(start_image)

    current_count, current_output = count_people(current_image)

    missing = expected_count - current_count

    if missing <= 0:
        status = "✅ SAFE - All Tourists Present"
    else:
        status = f"⚠ ALERT - Missing Tourists: {missing}"

    report = f"""
Expected Tourists : {expected_count}

Current Tourists : {current_count}

Missing Tourists : {max(missing,0)}

Status : {status}
"""

    return (
        start_output,
        current_output,
        report
    )


# =====================================================
# GRADIO UI
# =====================================================
demo = gr.Interface(
    fn=verify_group,
    inputs=[
        gr.Image(type="numpy", label="group_start.jpg"),
        gr.Image(type="numpy", label="current_group.jpg")
    ],
    outputs=[
        gr.Image(label="Start Group Detection"),
        gr.Image(label="Current Group Detection"),
        gr.Textbox(label="TourGuard Report")
    ],
    title="TourGuard AI",
    description="Tourist Verification System"
)

demo.launch(share=True)

# =====================================================
# TOURGUARD AI
# Tourist Verification System
# Google Colab + Gradio + YOLO11m
# =====================================================

# =====================================================
# INSTALL
# =====================================================
!pip install -q ultralytics gradio opencv-python-headless

# =====================================================
# IMPORTS
# =====================================================
import cv2
import gradio as gr
from ultralytics import YOLO

# =====================================================
# LOAD MODEL
# =====================================================
model = YOLO("yolo11m.pt")

# =====================================================
# PERSON COUNT FUNCTION
# =====================================================
def count_people(image):

    results = model.predict(
        image,
        conf=0.15,
        imgsz=1280,
        verbose=False
    )

    count = 0

    for box in results[0].boxes:

        cls = int(box.cls[0])

        # COCO class 0 = person
        if cls == 0:
            count += 1

    annotated = results[0].plot()

    annotated = cv2.cvtColor(
        annotated,
        cv2.COLOR_BGR2RGB
    )

    return count, annotated

# =====================================================
# TOUR VERIFICATION LOGIC
# =====================================================
def verify_group(start_image, current_image):

    # Count persons in starting image
    expected_count, start_output = count_people(start_image)

    # Count persons in current image
    current_count, current_output = count_people(current_image)

    # Difference
    difference = current_count - expected_count

    # =================================================
    # CASE 1 : PERFECT MATCH
    # =================================================
    if difference == 0:

        status = "✅ PERFECT MATCH"

        report = f"""
Expected Tourists : {expected_count}

Current Tourists : {current_count}

Missing Tourists : 0

Extra Persons : 0

Status : {status}
"""

    # =================================================
    # CASE 2 : MISSING TOURISTS
    # =================================================
    elif difference < 0:

        missing = abs(difference)

        status = f"⚠ ALERT - Missing Tourists : {missing}"

        report = f"""
Expected Tourists : {expected_count}

Current Tourists : {current_count}

Missing Tourists : {missing}

Extra Persons : 0

Status : {status}
"""

    # =================================================
    # CASE 3 : EXTRA PERSONS
    # =================================================
    else:

        extra = difference

        status = f"⚠ ALERT - Extra Persons Detected : {extra}"

        report = f"""
Expected Tourists : {expected_count}

Current Tourists : {current_count}

Missing Tourists : 0

Extra Persons : {extra}

Status : {status}
"""

    return (
        start_output,
        current_output,
        report
    )

# =====================================================
# GRADIO INTERFACE
# =====================================================
demo = gr.Interface(
    fn=verify_group,

    inputs=[
        gr.Image(
            type="numpy",
            label="Tour Start Photo (group_start.jpg)"
        ),

        gr.Image(
            type="numpy",
            label="Current Group Photo (current_group.jpg)"
        )
    ],

    outputs=[
        gr.Image(
            label="Start Group Detection"
        ),

        gr.Image(
            label="Current Group Detection"
        ),

        gr.Textbox(
            label="TourGuard AI Report",
            lines=12

        )
    ],

    title="🚌 TourGuard AI",

    description="""
AI-Based Tourist Verification System

✔ Counts tourists in starting image
✔ Counts tourists in current image
✔ Detects missing tourists
✔ Detects extra persons
✔ Generates verification report
"""
)

# =====================================================
# LAUNCH
# =====================================================
demo.launch(share=True)

"""show where Gradio stored the flagged data."""

!find . -iname "*flag*"

"""show where Gradio stored the flagged data."""

import os

for root, dirs, files in os.walk("."):
    if "flagged" in root.lower():
        print(root)
        for f in files:
            print("  ", f)

"""First check the exact file path:"""

!find . -name "*.csv"

"""To see all columns:"""

import pandas as pd

df = pd.read_csv("./.gradio/flagged/dataset1.csv")

print(df)

"""To see all the columns and complete content, run:"""

import pandas as pd

df = pd.read_csv("./.gradio/flagged/dataset1.csv")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

print(df)

"""To see only the column names:"""

print(df.columns)

"""To see the TourGuard report that was saved"""

print(df.iloc[0])

"""To see the second flagged record:"""

print(df.iloc[1])

"""To see the TourGuard report that was saved"""

print(df["TourGuard AI Report"])

"""To verify its exact location, run"""

!find . -name "dataset1.csv"

"""Download the CSV"""

from google.colab import files

files.download("./.gradio/flagged/dataset1.csv")